# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FakeWeChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'QMUIKit'

  pod 'Masonry', '~> 1.1'

  pod 'YYKit'

  pod 'YogaKit', '~> 1.7'

  target 'FakeWeChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FakeWeChatUITests' do
    # Pods for testing
  end

end
